# Generated by Django 5.0.2 on 2024-04-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='expected_end_balance',
            new_name='current_balance',
        ),
    ]
