# Generated by Django 5.0.2 on 2024-04-26 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_semester_semester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 4, 26)),
            preserve_default=False,
        ),
    ]
