# Generated by Django 5.0.2 on 2024-05-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_expense_end_date_income_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_last_updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_last_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
